### ISSUE TITLE
Python Implementation of N2O emissions from managed soils from IPCC

### ISSUE THREAD

**Issue by RomainBes** [ReScience/ReScience#115]
Dear ReScience journal, 

Over the last month, we developped a python implementation of the formula provided by the [IPCC report dealing with N2O emissions](https://www.ipcc-nggip.iges.or.jp/public/2019rf/pdf/4_Volume4/19R_V4_Ch11_Soils_N2O_CO2.pdf).
Those formulas involved many geospatialised parameters. 

To calculate the emissions, in the context of bioenergy production, we developped a small python module composed of 4 submodules that:
- Download the input data from various API (FAO, Eurostat, FUBC, etc),
- Calculate the emissions based on the IPCC formulas,
- Analyse the emissions (by countries, by crops, by source of emissions...),
- Visualize both the input and output data.

We would like to publish this work in an open science journal and make it accessible to the research community.

We are considering publishing in your journal but we are not sure that it would fit the scope as it is more an implementation of the existing work from IPCC, that would make our work and the N2O calculation reproducible, than a reproduction in itself of an existing scientific work as the IPCC report do not contain results that could be reproduced but only the recommanded method to estimate those emissions.

Thanks in advance for sharing your point of view on the situation to know if such an "implementation" paper would fit in the scope of the journal.

Best,

**Comment by khinsen** [comment]
Thanks for your enquiry! Pinging all @ReScience/editors for comments.

What you are doing is very much in the spirit of ReScience C. Providing a working implementation for previously published methods is an important part of replication work. It's just that you are "replicating" a paper with a methods section but no results, not even examples.

A practical issue I see with reviewing your work, here or elsewhere, is that in the absence of test cases, the only reviewing approach I see is careful proofreading of your code, comparing with the equations in the report. That's rather different from standard ReScience C reviews, so I am not sure our reviewers would be at ease with it.

**Comment by RomainBes** [comment]
Thanks for your answer. I'll discuss the decision with my colleagues.

**Comment by pdebuyl** [comment]
Hello, indeed in ReScience C we typically compare some output (figures, tables, etc). If the lack of openness is beyond the software (i.e. in the methods), it would make sense to publish your work in a more traditional journal. You have options to make the code a companion of this, such as a dedicated zenodo archive with all code (etc). Others would cite your journal article but would have access to the full software.

**Comment by khinsen** [comment]
@RomainBes Some more thoughts...

One option you have is submitting your code to the [Journal of Open Source Software](https://joss.theoj.org/). Among the requirements of JOSS is a test suite. Do you have one? What does it test? In particular, what is the source of ground truth you test against?

The only technique I can think of to actually verify your code is to have a completely independent team write a second implementation, based on the IPCC report, and then run extensive comparisons of the two implementations. If the results agree, the probability of a mistake is small since both teams would have had to make the same mistake independently.

The party to blame is of course IPCC. Publishing a large set of mathematical equations without any reference examples means that everybody wishing to use the equations has a big verification problem.
