### ISSUE TITLE
Full affiliation for editors

### ISSUE THREAD

**Issue by rougier** [ReScience/ReScience#51]
Dear @ReScience/associate-editors @ReScience/editors,

We've applied for membership to the [Open Access Scholarly Publishers Association](http://oaspa.org) and for this, we need to have the full affiliation (including department) for each of you, this will be displayed on the board page. We could also have a small text introducing yourself + a photo just like for the [JOSS board](http://joss.theoj.org/about#editorial_board).

If you're ok (small text + photo), just add a 👍 here and reply here with the relevant information.
Else, I would still need you full affiliation.

**Comment by labarba** [comment]
You can use my JOSS blurb.

**Comment by rougier** [comment]
Ok, I just added affiliations for everybody.

**Comment by oliviaguest** [comment]
Looks very snazzy! :clap:

**Comment by benureau** [comment]
As a simple reviewer, I am jealous.

**Comment by rougier** [comment]
Any taker for https://github.com/ReScience/rescience.github.io/issues/33

Since I wrote the original text, I may be not the best to correct the page...

**Comment by rougier** [comment]
@benureau Sorry for that, this would be too much work (or do you fell collecting the information ?)
@oliviaguest Thanks !

**Comment by khinsen** [comment]
Photo - is the one from my GitHub profile good enough? Otherwise, this will have to wait for next week.

Text:

Researcher at the [Centre de Biophysique Moléculaire](http://cbm.cnrs-orleans.fr/) in Orléans (France) and at the [Synchrotron SOLEIL](http://www.synchrotron-soleil.fr/) in Saint Aubin (France). Main research topics: physics of biomolecules, scientific computing. Member of the editorial board of [Computing in Science and Engineering](http://www.computer.org/cise/).

**Comment by rougier** [comment]
@khinsen In the end, I've put only a minimal version online for all of us.

**Comment by rougier** [comment]
@khinsen Could you have a look a the [edit](http://rescience.github.io/edit/) webpage for possible improvements/corrections?

**Comment by khinsen** [comment]
@rougier Done!

**Comment by karthik** [comment]
Also please use my JOSS blurb. thanks!
