### ISSUE TITLE
Publons

### ISSUE THREAD

**Issue by anne-urai** [ReScience/ReScience#63]
Hi all,

Publons is a platform to track researchers' editing and reviewing activities, which can be linked to ORCID and displayed as part of a resumé. ReScience has a profile https://publons.com/journal/44652/rescience but it looks unclaimed.

It may be interesting to use the Publons service, list ReScience as a journal there and allow reviewers (and editors) to add ReScience contributions to their list of other reviewing activities.

**Comment by rougier** [comment]
Great idea. What would it take to register ReScience ?

**Comment by anne-urai** [comment]
The information I can find here https://publons.freshdesk.com/support/solutions/articles/12000012231-what-is-publons-and-why-partner-with-us-  says that for publishers, it's sufficient to email partnerships@publons.com and requesting to be a partnership journal. I'm not 100% sure how it would work for ReScience since there is not an official publisher, but I would think emailing them would be a good first step. There does not seem to be more information available about this application process.

**Comment by khinsen** [comment]
Before the summer break there was some noise about Publons having been acquired by Clavirate (ex Thomson Reuters, owner of Web of Science etc.), leading to suspicion that it might move to the "dark side" of scientific publishing. I didn't really follow those discussions, so I have no opinion, but it may be worth some investigation. Otherwise I am all for ReScience contributors getting maximum benefit from their contributions.

**Comment by rougier** [comment]
Read here: https://www.thebookseller.com/news/clarivate-analytics-buys-publons-562691

**Comment by pdebuyl** [comment]
Given the age of the issue *and*, of course, the opposition between ReScience's ideals and the business model of Clarivate we can close this?
