### ISSUE TITLE
Journal organisation

### ISSUE THREAD

**Issue by rougier** [ReScience/ReScience#7]
I opened a new issue concerning the overall journal organisation and review process.
Mehdi posted a lot of comments in his review but these comments would be better discussed here since the PR (https://github.com/ReScience/ReScience-submission/pull/3) will be closed at some point.

Mehdi, could you post your comments below ?

@khinsen @MehdiKhamassi @otizonaizit @benoit-girard

**Comment by MehdiKhamassi** [comment]
Dear Nicolas,

Thank you for opening this new issue.
Here are a few questions and comments that concern the global organization of the journal, although they have been raised during the review of the submitted paper by Topalidou and Rougier (https://github.com/ReScience/ReScience-submission/pull/3). I hope that these questions and comments can help improving the organization of the review process for the ReScience journal in general. This section also includes some technical issues I ran through, aiming at helping future reviewers who could face the same issues.

In the following, I define:

-    "submitted article", "submitting authors", "submitted code" as a paper presenting a re-implementation of an already published computational model and submitted for consideration for publication in ReScience, and the related python code that the submitting authors attached to the submission.
-    "original article", "original authors", "original code" as the paper previously published which originally proposed the considered computational model.


Is an article submitted to ReScience acceptable if it only reproduces a subpart of the figures of the original article, or even a single figure? Shouldn't a justification in this case be explicitly required in the submission guidelines of the journal? In the case of partial reproduction of the results of the original article, shouldn't the submitted article include guidance, tips and suggestions to help a reader use the submitted code to reproduce additional results not included in the submitted article?



In the submitted paper by Topalidou and Rougier, it is written: "We provide below the formal description of the model according to the proposition of Nordlie et al. [2] for reproducible descriptions of neuronal network models. [...] [2] E. Nordlie, M. Gewaltig, and H.E. Plesser. “Towards reproducible descriptions of neuronal network models”. In: PLoS Computational Biology 5.8 (2009), e1000456. doi: 10 . 1371 / journal.pcbi.1000456."
Shouldn't this constitute a referenced proposition to follow in the submission guidelines of ReScience for the authors? This could help standardize the way models are described in ReScience journal.

Questions concerning the possible accessibility of the original code of the model proposed by the original authors: If the original code is accessible online, shouldn’t it be explicitly required in the review guidelines that the reviewers of an article submitted to ReScience – which presents a re-implementation of the original code in order to reproduce the results of the original article – download the original code so as to verify that the submitted code is a real re-implementation and not a clone of the original code?
If the original code is already written in python, is it worth accepting for publication in ReScience an article which presents yet another python implementation? Maybe the answer to this question could be yes if there were errors in the original code or in the original article which deserved to be corrected and officially published in ReScience after correction in order to be accessible to the community?
Same question in the case where the original code was already implemented in python plus it is accessible online.

It would be useful for reviewers if the following paragraph from Editor guidelines was also included in the Review guidelines: “The main criterion for acceptation is the actual replication of the research with a clear statement by the authors explaining why they think they have replicated the paper (same figures, same graphics, same behavior, etc.). However, keep in mind that the clarity of the code is an important criterion. Uncommented or obfuscated code is as bad as no code at all. A code without the accompanying article is also a criterion for rejection since we're not human compilers (well not all of us at least).”

I think it is very important to explicitly ask the reviewers to verify that the submitted code to ReScience is a real and honest re-implementation of a original computational model and not a simple code written to build point by point, line by line, a fake figure(s) which look(s) like figure(s) in the original article. Without such warning explicitly written in the ReScience guidelines, it is not clear that this is not acceptable for publication, although it is implicitly obvious to any researcher in the community.

Online access to the submission
I find it difficult to access to the submitted paper on the web, as well as to the code source of its implemented model.
First, when accessing the following page: https://github.com/ReScience/ReScience-submission, I could not access the pdf of the submitted article but just a template. Once on the following page: #3, I cannot find any link to access the pdf of the article nor the source code. Currently, the only way I can access them is by going to the clone of the git repository I have on my computer. This was even difficult to get on my computer (see other technical issues I faced below). I think it should be straightforward to access the pdf of the article and the source code but from the website and from the review invitation email (see below).
Also, when a pdf is accessible from ReScience website, it is currently through a “RAW” button which I think should be changed to be more easily understandable as something like: « Download pdf version of the submitted article ».

Again, concerning access to information as a reviewer for ReScience, I think that, after having accepted to review an article for the journal, a single email should be sent to the reviewer will all information and all links to access the pdf of the article, the source code, how to get a clone of the git repository on the reviewer’s own computer (so as to simulated the model himself), and how to access the forum so as to post questions, comments and decisions.
This single email should also include information that @rougier sent me in French (I let you translate, Nicolas): “Vous devriez pourvoir éditer le tout premier message pour rajouter votre nom derrière "Review 1 started" ou "Review 2 started" et aussi cocher la case. Pour les message que vous posterez, ça serait bien de le commencer par "REVIEWER 1" (ou 2 selon) histoire de rendre le thread plus clair pour tout le monde. »
This single email should also include the following lines taken from #3:
« The repository lives at https://github.com/rougier/ReScience-submission/
$ git clone https://github.com/rougier/ReScience-submission.git
$ cd ReScience-submission
$ git checkout topalidou-rougier »

Technical issue(s) I ran through before being able to do my review:

First, as a SVN user, I am not familiar with git. I thought it would be straightforward having briefly seen my collaborators perform very similar checkout or commit commands. But it was not that easy here.

First it was not clear to me whether I had to download the code from github after being connected on it, or whether I had to write a “git clone …” command from a terminal on my computer. It was also not clear whether there might be a conflict on my computer if I did both. Or even whether it was necessary to specify my github user account when writing the “git clone …” commands in a terminal.

Also, I have a git version 1.9.1, which apparently does not accept the “git co” command, but only the “git checkout” command. So maybe the instructions on ReScience should include the latter rather than the former.

Finally, once I managed to run the « git checkout topalidou-rougier » command, it said that “topalidou-rougier” should be put in the “origin” but not in the folder were I was currently (i.e. ReScience-submission). I did not understand what that meant, unsuccessfully did some “locate topalidou-rouger” command, etc... In the end, @rougier told me by email that the ReScience-submission folder already contains the topalidou-rougier code in the “code” subfolder, and their article in the “article” subfolder, which have now replaced the template “code” and “article” subfolders once I have performed the “git checkout topalidou-rougier” command.
So it should be made clearer for the reviewer that she can then access the code and the article simply by browsing these subfolders.

This raises another question: what happens if I later perform a second review for ReScience and do a “git checkout paper2” command? Will this erase and replace the code for the topalidou-rougier paper? What if I want to keep both papers in my git folder?
Finally, it should be clearly written in the single review access email and on the website that the instructions to run the code of a submitted paper (once “git checkout …” has been performed on the reviewer’s computer) are in ReScience-submission/code/README.md.

SMALL typo on the website:
In the wiki of ReScience, “how to submit ?” should read “how to submit?” (without space before the question mark).

@khinsen @rougier @otizonaizit @benoit-girard

**Comment by khinsen** [comment]
Thanks @MehdiKhamassi for this detailed feedback!

As for partial replication, I think we should clearly admit this if the replicated part is substantial enough to be of interest. It would be the reviewers' job to advise on this, and the authors should be required to state explicitly which parts have been replicated, and why they chose that particular subset.

In my experience it is quite frequent that only a part of the results is documented well enough for replication. It is also frequent to have some relevant and some much less relevant results in a paper, so it makes sense in a replication to concentrate on the relevant parts.

Your suggestion to standardize model descriptions and references is a good one in principle, but I wonder if this can be done at the current stage of ReScience. We should look at this perhaps a year from now, after some experience in real life.

Comparing to the original code, where available, makes sense indeed, both for potential plagiarism and to judge if the new implementation has any real advantages. A less obvious question is if we should ask reviewers to actively search for such code, even if the submitted papers makes no reference to it.

On the other hand, I don't think fraudulous submissions (pirated code, fake replication, etc.) are our main problem at this time. This may happen when ReScience reaches the impact factor of Nature ;-)

Facilitating access to the PDF should not be a problem. I am not sure though if we can avoid the "RAW" button, as long as the PDF is stored in the Git repository. We could also explore recommending reviewers to download a snapshot of the repository, which would contain the PDF and the code. If we can standardize the repository layout to make these easy to find, that may well be a good solution. Reviewers should definitely not have to use Git. I'd even go further and say that reviewers should not be encouraged to use Git. Those who are Git experts don't need any advice about using GitHub, and those who aren't would probably be happy not to have to deal with Git.

**Comment by rougier** [comment]
@MehdiKhamassi

Thanks a lot for this feedback. I will just complete Konrad answer.

I've started modifying the wiki and the submission/review procedure, taking your comment into account. I will answer your questions in random order:

* For the standardized model description, I think this should be the role of the editor to appreciate if there exist some recommendation in the domain. Don't forget ReScience is not specifically targeted at computational neuroscience but any computational science actually. Such recommendations may thus vary a lot across domains.

* PDF access should now be simplified by having a simple link in the initial PR text. Note also that the PDF is also accessible from within the repository once forked.

* If you make a second review for ReScience, you should be able to checkout the new submission using a different branch name. But I now realize this requires you to first fork the original ReScience directory. I will update instructions in the reviewer guideline.

* I added a git guide in the reviewer guideline


Concerning the control of the actual replication, I think we may need more experience in the various computational domains in order to have a better idea on what could be the actual problems. I think for the time being, editor and reviewers should appreciate themselves if the submission is an actual replication and provide enough material to control it.

**Comment by otizonaizit** [comment]
@rougier @khinsen : are you going to be at EuroSciPy in two weeks? If yes, we could schedule a short meeting to discuss a bit these issues? We would of course later post the minutes of the meeting to this issue so that they are public.

**Comment by rougier** [comment]
I will and yes we can talk about that during EuroScipy. I think Konrad won't attend but we can post here result of the discussion.
