### ISSUE TITLE
Use of Gitlab

### ISSUE THREAD

**Issue by Kahsius** [ReScience/ReScience#98]
Hello all,

I would like to know if you accept the use of Gitlab as a repository for the presented code.
Regarding what is written in the metadata.yaml file, the code requires a DOI, which we can get through Zenodo for Github repositories. However I haven't figured out how to get one for Gitlab repositories.

To sum up:
- is the DOI for the code mandatory ?
- if yes, how can I get one for my Gitlab repository ?

Best regards !

**Comment by khinsen** [comment]
When you say "GitLab", do you mean http://gitlab.com/, or some GitLab site hosted elsewhere?

There is no problem with using GitLab either way, we have had such submissions already (see e.g. https://github.com/ReScience/submissions/issues/22 or https://github.com/ReScience/submissions/issues/32, which both refer to code stored an on an instutional GitLab instance). What matters is that the repositories are public.

For the final version of the code, we do indeed require a DOI or a SWHID. DOIs are easiest to get for GitHub repositories via Zenodo, but it's OK if you download a zipped or tarred archive of your repository state and submit it manually to Zenodo (or elsewhere). SWHIDs are easiest to get for GitHub and gitlab.com (both sites being archived automatically), but again you can submit your code yourself from any public Git repository (see https://archive.softwareheritage.org/save/).

If you hesitate between DOI and SHWID, go for SWHID. It's more useful because it gives access to all of the code's history.

**Comment by Kahsius** [comment]
It totally answers my question, thank you very much !
